### ISSUE TITLE
Warning: 'End of processing at large atom (LargeFileSupport not enabled)'

### ISSUE THREAD

**Issue by medikoo** [photostructure/exiftool-vendored.js#109]
**Describe the bug**

I've tried to retrieve EXIF data from 2GB+ movie file, and got `End of processing at large atom (LargeFileSupport not enabled)` warning in return data.

Is there any way to enable large file support?

**Environment (please complete the following information):**
 - macOs 12.1
 - Node.JS: 14.19.1

**Comment by mceachen** [comment]
When you build your instance of `ExifTool`, you can give it arguments. The default is `["-stay_open", "True", "-@", "-"]`: you could try `["-api", "largefilesupport=1", "-stay_open", "True", "-@", "-"]` (but I don't have a way to verify this works...)

**Comment by mceachen** [comment]
You can also try setting up a config file for `exiftool`: see this forum post for details:

https://exiftool.org/forum/index.php?topic=3916.0

**Comment by medikoo** [comment]
> (closing as this is a config issue for exiftool rather than a coding issue for this module.)

This plugin embeds `exiftool` (it's not that the user installs it separately and then uses this module with it). So it'll be good to provide some hint on how this embedded ExifTool can be additionally configured. Currently, it's not clear to me. 
I see two dependencies hosting it, `exiftool-vendored.exe` and `exiftool-vendored.pl`, where can I find the mentioned config file?

**Comment by mceachen** [comment]
The path to a config file is described here:

https://github.com/photostructure/exiftool-vendored.js/issues/27#issuecomment-413924476

**Comment by medikoo** [comment]
After some fiddling, I've found that it works without any extra settings if `.ExifTool_config` with following content is placed at current working directory, large file support will be enbled

```perl
%Image::ExifTool::UserDefined::Options = (
    LargeFileSupport => 1,
);
```

Otherwise, as pointed in above comment, path to config file can be passed as first argument:

```javascript
new ExifTool({
	exiftoolArgs: [
		"-config", path.resolve(os.homedir(), ".ExifTool_config"), "-u", "-stay_open", "True", "-@",
		"-"
	]
});
```

**Comment by stephen304** [comment]
So it turns out the reason that `["-api", "largefilesupport=1", "-stay_open", "True", "-@", "-"]` doesn't work is because `stay_open` mode resets the flags after each `-execute`, so lfs will only be enabled for the first operation. I was able to solve it without a config file by passing the flags to `read` instead of the constructor:

```
exiftool.read(path, undefined, {
    ...DefaultReadTaskOptions,
    // Enable exiftool LFS to parse metadata for files larger than 2GB.
    optionalArgs: ['-api', 'largefilesupport=1'],
});
```

Note that passing in args in the second parameter (`optionalArgs`) doesn't work because it gets overwritten when constructing the ReadTaskOptions here (at least when I move optionalArgs to the end of the object it gets passed through so I assume it's being clobbered by the other 2 entries):

https://github.com/photostructure/exiftool-vendored.js/blob/ece7bcd11d2c3c1dc8af0fbd57d768220f0dd243/src/ExifTool.ts#L292-L296

**Comment by mceachen** [comment]
Oh crap! I'll get this fixed, thanks for the research, @stephen304 !

**Comment by stephen304** [comment]
@mceachen I probably should have provided more context - I just now realized that the second parameter is probably only supposed to be used if you aren't using the third to pass in a ReadTaskOptions object.

The full code in immich is:
```js
exiftool
      .read(path, undefined, {
        ...DefaultReadTaskOptions,

        defaultVideosToUTC: true,
        backfillTimezones: true,
        inferTimezoneFromDatestamps: true,
        useMWG: true,
        numericTags: [...DefaultReadTaskOptions.numericTags, 'FocalLength'],
        /* eslint unicorn/no-array-callback-reference: off, unicorn/no-array-method-this-argument: off */
        geoTz: (lat, lon) => geotz.find(lat, lon)[0],
      })
```

And since geoTz is a function, passing string array of options as the second parameter doesn't work - so that's why I guess they are passing in undefined as the second parameter and led to the confusion when I tried to combine your previous suggestion while still passing the rest of the arguments in as an object.

**Comment by mceachen** [comment]
Given that the current API is a bit confusing, I'm actually going to add the `readArgs` to `ExifToolOptions`, and have adjusted the jsdocs accordingly:

```ts

  /**
   * Read the tags in `file`.
   *
   * @param {string} file the file to extract metadata tags from
   *
   * @param {string[]} [readArgs] any additional ExifTool arguments, like
   * `["-fast"]`, `["-fast2"]`, `["-g"]`, or `["-api", "largefilesupport=1"]`.
   * Note that providing a value here will override the `readArgs` array
   * provided to the ExifTool constructor. **Note that most other arguments will
   * require you to use `readRaw`.** Note that the default is `["-fast"]`, so if
   * you want ExifTool to read the entire file for metadata, you should pass an
   * empty array as the second parameter. See https://exiftool.org/#performance
   * for more information about `-fast` and `-fast2`.
   *
   * @returns {Promise<Tags>} A resolved Tags promise. If there are errors
   * during reading, the `.errors` field will be present.
   */
  read<T extends Tags = Tags>(
    file: string,
    readArgs?: string[],
    options?: ReadTaskOptions
  ): Promise<T> {
```
