### ISSUE TITLE
Setting ModifyDate does not work (shows the date when the file was modified by exiftools)

### ISSUE THREAD

**Issue by gltched-usr** [photostructure/exiftool-vendored.js#186]
**Describe the bug**
When I try to set the ModifyDate it doesnt work, Instead it shows the date when the file was modified by exiftool-vendored

**To Reproduce**
```js
function updateExifCreateDate(filePath, date){
    try {
        const timestamp = date.toISOString();
        await exiftool.write(filePath, {
            CreateDate: timestamp, // Update the creation date
            ModifyDate: timestamp
        }, ['-overwrite_original']); // Pass the flag as an array of strings
        console.log(`Updated EXIF CreateDate for ${filePath} to ${timestamp}`);
    } catch (error) {
        console.error(`Error updating EXIF CreateDate for ${filePath}:`, error);
    }
};
```
Windows explorer shows the updated CreateDate but the ModifyDate is the time the file was modified:
![image](https://github.com/photostructure/exiftool-vendored.js/assets/126079750/bef60700-e7b2-4498-94a8-86cb967951ee)

**Expected behavior**
The ModifyDate should be set to the same date as the CreateDate

**Environment (please complete the following information):**
 - Version of this library: 26.2.0
 - OS and version: Windows 11
 - Node.js version: 22.2.0

**Comment by mceachen** [comment]
There are so many dates associated to a single file, it's easy to confuse them!

`ModifyDate` is one of (many!) EXIF tags that can encode the "captured at" time of a photo. If you're interested, I wrote more about this here: https://photostructure.com/faq/captured-at/

Windows Explorer is showing the _filesystem's_ last-modified date, rather than something encoded in the file's metadata headers. ExifTool encodes this as `FileModifyDate`.
