### ISSUE TITLE
Use without vendored

### ISSUE THREAD

**Issue by hughevans** [photostructure/exiftool-vendored.js#56]
**Is your feature request related to a problem? Please describe.**

Ironically this library has the best JS wrapper API around Exiftool and I’d love to use it with pre-installed `exiftool`.

**Describe the solution you'd like**

The ability to install the library without also installing a vendored dependency of exiftool.

**Additional context**

I’m running this in Lambda and after attempting the solutions proposed in #53 with no luck I ended up creating my own [Lambda layer](https://gist.github.com/hughevans/6b8c57839b8194ba910428de4375794a). I can’t use this library now though because it expects exiftool-vendored.pl to be there.

**Comment by mceachen** [comment]
> Ironically this library has the best JS wrapper API around Exiftool 

![Thanks...?](https://media.giphy.com/media/VsKu4TW2w09O/giphy.gif)

This is actually the third wrapper I've written for ExifTool, and there are a couple of sticky bits here.

Prior wrappers didn't require vendoring ExifTool, which led to people running ancient versions that it didn't work well with. ExifTool's output changes, I don't want to support N versions.

The other sticky bit: packaging. If, say, the code is moved to a new `@photostructure/exiftool` package that omits the vendored dependency, and make this package just require and export `@photostructure/exiftool` and require the vendored ExifTool, I think we get what you want, but the new package should probably grump if the version of exiftool isn't "close enough" to supported versions. That starts to smell like a monorepo (using Lerna?) would be needed to coordinate all those sub-packages.

I don't have time to make that happen right now. If you want to work on it, PRs are welcome, and feel free to push work-in-progress PRs if you want feedback before you're done.

**Comment by mceachen** [comment]
If you'd like to tackle this, feel free to reopen.

**Comment by hughevans** [comment]
Thank you. I’ll try and get you a PR in the next week.

**Comment by mischuler** [comment]
@hughevans Did you ever get a working Lambda layer version of this working? I've had one working until I've moved from NodeJS 8.10 to Node 12x as 8.10 LTS is being deprecated. Now I can't even get the version command to work. Running any command (`version` or `read`) causes the Lambda to terminate without an error code.

I have a layer very similar to the layer you created in your Aug 12 comment. I've packaged the exiftool.vendored.pl as a stand-alone file
In my package lock: ` "exiftool-vendored.pl": "file:vendor/exiftool-vendored.pl",`, where the .pl is file is just `module.exports = "/opt/exiftool/exiftool";`. perl is my /opt/bin/ and exiftool is in /opt/exiftool/

@mceachen Is it expected behavior that no error message would be returned if there's a problem? I'm guessing it's something with how I have things packaged within the layer, but the lack of any feedback is making debugging a bit tricky.

I'm currently on version 8.13.1 with ExifTool 11.51.

**Comment by mceachen** [comment]
> @mceachen Is it expected behavior that no error message would be returned if there's a problem? 

No.

> I'm guessing it's something with how I have things packaged within the layer, but the lack of any feedback is making debugging a bit tricky.

Have you enabled logging? There's an example here: https://github.com/photostructure/exiftool-vendored.js/blob/master/src/_chai.spec.ts#L15

**Comment by boustanihani** [comment]
> [@mceachen](https://github.com/mceachen) Is it expected behavior that no error message would be returned if there's a problem? I'm guessing it's something with how I have things packaged within the layer, but the lack of any feedback is making debugging a bit tricky.

I'm also getting no error messages as described in this issue:
https://github.com/photostructure/exiftool-vendored.js/issues/279

The Lambda function is simply getting a timeour error..
Running `await exiftool.version()` never ends.. I already added a Perl layer..

All of this happend suddenly, in the last weeks it was working with no errors..
