### ISSUE TITLE
Option to "overwrite_original"

### ISSUE THREAD

**Issue by mrbrahman** [photostructure/exiftool-vendored.js#64]
During writes, exiftool provides an option `-overwrite_original`, which won't keep the `_original` file. I can't seem to find a way to use that feature here. Can you please help?

If that feature is not yet supported, It'll be great if it can be added.

Thanks!

**Comment by mceachen** [comment]
Your github profile looks like you're starting a self-hosted photos app: you might want to try out [PhotoStructure](https://blog.photostructure.com/introducing-photostructure/)!

FWIW I specifically don't use it for PhotoStructure due to the risk from exiftool potentially corrupting original images.

If you want to add support for this, with tests and an appropriate warning, I would accept the PR.

**Comment by JakobJingleheimer** [comment]
For anyone coming to this now, this is possible (at least as of v14.2.0):

```js
import {
  DefaultExiftoolArgs,
  DefaultExifToolOptions,
  ExifTool,
} from 'exiftool-vendored';

const exiftool = new ExifTool({
  ...DefaultExifToolOptions,
  exiftoolArgs: [
    ...DefaultExiftoolArgs,
    '-overwrite_original',
    // other CLI arguments
  ],
});
```

The _original files are superfluous in my case because I'm already feeding exiftool a clone of the original.

**Comment by mceachen** [comment]
Thanks for the tip, @JakobJingleheimer!

**Comment by JakobJingleheimer** [comment]
Thanks for the well made library with good exports that made it possible 🙌

But on a related note: my trick just mysteriously stopped working (I made a change and it stopped working, so I reverted back to the working commit, but still broken). Is there some kind of cache that might be at play?

**Comment by mceachen** [comment]
> Is there some kind of cache that might be at play?

Nope, this library doesn't implement any caching, nor does ExifTool.
