### ISSUE TITLE
Emojis not supported in tags

### ISSUE THREAD

**Issue by grod220** [photostructure/exiftool-vendored.js#87]
**Describe the bug**
Whenever an emoji is used, it does not write tags properly.

**To Reproduce**

```
exiftool.write(`myfile.jpg, {
  Description: '🦍 hello world',
});
```

This will produce a new file with the field written as `?????? hello world`. I believe it is corrupting the field.

**Expected behavior**
Expected the field to save the emoji character.

**Environment (please complete the following information):**
 - OS and version: Mac OS X Catalina
 - Node.JS version: v15.0.1

**Comment by mceachen** [comment]
Thanks for the report! 

FWIW, "simple" emoji are supported, but compound emoji are not currently. I'll fix this now.

<pre>  1) WriteTask
       round-trip with an image
         round-trips a comment with an emoji:
      <font color="#CC0000">-⌚✨??????????????????????????????‍??????‍????????????‍♀️ Sun Jan 10 2021 13:48:52 GMT-0800 (Pacific Standard Time)</font>
      <font color="#4E9A06">+⌚✨🦏🌈🦍🦄🧑‍🤝‍🧑🚵‍♀️ Sun Jan 10 2021 13:48:52 GMT-0800 (Pacific Standard Time)</font>
</pre>

**Comment by mceachen** [comment]
Crap: it's because of my home-grown html entity encoder (that I wrote to avoid external dependencies). If I switch it out for he, everything works.

[he](https://github.com/mathiasbynens/he) is used by 4.2 million projects, and it only [adds 73.8 kB](https://bundlephobia.com/result?p=he@1.2.0), so I think that's the better solution.

I'm publishing the fix now.

Thanks again for the bug report!
